name: clang-format Check

on:
  push:
  pull_request:

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: clang-format Check
        uses: jidicula/clang-format-action@v4.13.0

