name: Catch2 Testing

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: run-cmake
        uses: lukka/run-cmake@v10.7

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: |
          cd build/tests
          ctest --output-on-failure
