name: Catch2 Testing

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v4

      - name: Configure and Build Project
        uses: threeal/cmake-action@main
        with:
          generator: Ninja
          c-compiler: clang
          cxx-compiler: clang++
          options: -DBUILD_BINARY=OFF -DBUILD_TESTS=ON

      - name: Run tests
        run: |
          cd build/tests
          ctest --output-on-failure --verbose -j
