name: Catch2 Testing

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build -j $(nproc)

      - name: Run tests
        run: |
          cd build/tests
          ctest --output-on-failure --verbose -j
