name: Catch2 Testing

on: [ push, pull_request ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v4

      - name: Install dependencies
        run: |
          brew install boost

      - name: Install latest clang
        run: |
          brew install llvm
          clang --version

      - name: Configure and Build Project
        uses: threeal/cmake-action@main
        with:
          generator: Ninja
          c-compiler: /opt/homebrew/opt/llvm/bin/clang
          cxx-compiler: /opt/homebrew/opt/llvm/bin/clang++

      - name: Run tests
        run: |
          cd build/tests
          ctest --output-on-failure --verbose -j
